version: '3.8'

services:
  # Database for storing user accounts, routing data, rates, etc.
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-smppuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-smpppassword}
      POSTGRES_DB: ${DB_NAME:-smppdb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./deploy/docker/postgres/init:/docker-entrypoint-initdb.d # আপনার গাইডে এই ফোল্ডার এবং init স্ক্রিপ্ট নেই, কিন্তু docker-compose এ উল্লেখ আছে
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - smpp_network
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER:-smppuser}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and messaging
  redis:
    image: redis:7.0-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - smpp_network
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ for messaging and queuing
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-smppuser}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-smpppassword}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    networks:
      - smpp_network
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Core SMPP Server
  smpp-server:
    build:
      context: .
      dockerfile: ./deploy/docker/smpp-server/Dockerfile # এখানে Dockerfile এর পাথ উল্লেখ করা আছে
    depends_on:
      - postgres
      - redis
      - rabbitmq
    volumes:
      - ./configs/${ENV:-dev}/smpp-server.conf:/etc/smpp-server/smpp-server.conf # কনফিগারেশন ফাইলের পাথ
      - smpp_logs:/var/log/smpp-server
    ports:
      - "${SMPP_PORT:-2775}:2775"
    environment:
      - ENV=${ENV:-dev}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-smppdb}
      - DB_USER=${DB_USER:-smppuser}
      - DB_PASSWORD=${DB_PASSWORD:-smpppassword}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER:-smppuser}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-smpppassword}
    networks:
      - smpp_network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"] # Healthcheck এর জন্য API সার্ভিসের প্রয়োজন
      interval: 30s
      timeout: 10s
      retries: 3

  # Rate Management Service
  rate-manager:
    build:
      context: .
      dockerfile: ./deploy/docker/rate-manager/Dockerfile # এই Dockerfile এর কন্টেন্ট আপনার গাইডে দেওয়া নেই
    depends_on:
      - postgres
      - redis
      - rabbitmq
    volumes:
      - ./configs/${ENV:-dev}/rate-manager.conf:/etc/rate-manager/rate-manager.conf # কনফিগারেশন ফাইলের পাথ
      - rate_manager_data:/var/lib/rate-manager
    environment:
      - ENV=${ENV:-dev}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-smppdb}
      - DB_USER=${DB_USER:-smppuser}
      - DB_PASSWORD=${DB_PASSWORD:-smpppassword}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER:-smppuser}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-smpppassword}
      - SMTP_HOST=${SMTP_HOST:-smtp.example.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER:-user}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-password}
      - EMAIL_FROM=${EMAIL_FROM:-noreply@example.com}
    networks:
      - smpp_network
    restart: always

  # Billing and Invoicing Service
  billing:
    build:
      context: .
      dockerfile: ./deploy/docker/billing/Dockerfile # এই Dockerfile এর কন্টেন্ট আপনার গাইডে দেওয়া নেই
    depends_on:
      - postgres
      - redis
      - rabbitmq
    volumes:
      - ./configs/${ENV:-dev}/billing.conf:/etc/billing/billing.conf # কনফিগারেশন ফাইলের পাথ
      - billing_data:/var/lib/billing
      - invoice_templates:/var/lib/billing/templates # টেমপ্লেট ফাইলের পাথ
    environment:
      - ENV=${ENV:-dev}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-smppdb}
      - DB_USER=${DB_USER:-smppuser}
      - DB_PASSWORD=${DB_PASSWORD:-smpppassword}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER:-smppuser}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-smpppassword}
      - SMTP_HOST=${SMTP_HOST:-smtp.example.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER:-user}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-password}
      - EMAIL_FROM=${EMAIL_FROM:-noreply@example.com}
    networks:
      - smpp_network
    restart: always

  # Web API and Admin Interface
  api:
    build:
      context: .
      dockerfile: ./deploy/docker/api/Dockerfile # এই Dockerfile এর কন্টেন্ট আপনার গাইডে দেওয়া নেই
    depends_on:
      - postgres
      - redis
      - smpp-server # API সার্ভিসের জন্য SMPP সার্ভিসের প্রয়োজন
      - rate-manager # API সার্ভিসের জন্য Rate Manager সার্ভিসের প্রয়োজন
      - billing # API সার্ভিসের জন্য Billing সার্ভিসের প্রয়োজন
    volumes:
      - ./configs/${ENV:-dev}/api.conf:/etc/api/api.conf # কনফিগারেশন ফাইলের পাথ
      - api_logs:/var/log/api
    ports:
      - "${API_PORT:-8080}:8080"
    environment:
      - ENV=${ENV:-dev}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-smppdb}
      - DB_USER=${DB_USER:-smppuser}
      - DB_PASSWORD=${DB_PASSWORD:-smpppassword}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER:-smppuser}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-smpppassword}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret} # সিক্রেট কী প্রয়োজন
    networks:
      - smpp_network
    restart: always

  # Web UI
  web:
    build:
      context: .
      dockerfile: ./deploy/docker/web/Dockerfile # এই Dockerfile এর কন্টেন্ট আপনার গাইডে দেওয়া নেই
    depends_on:
      - api # Web UI এর জন্য API সার্ভিসের প্রয়োজন
    volumes:
      - ./configs/${ENV:-dev}/web.conf:/etc/nginx/conf.d/default.conf # Nginx কনফিগারেশন ফাইল
    ports:
      - "${WEB_PORT:-80}:80" # ওয়েব পোর্ট
    networks:
      - smpp_network
    restart: always

  # Monitoring and Alerting
  prometheus:
    image: prom/prometheus:v2.40.1
    volumes:
      - ./configs/${ENV:-dev}/prometheus.yml:/etc/prometheus/prometheus.yml # Prometheus কনফিগারেশন
      - prometheus_data:/prometheus
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090" # Prometheus ওয়েব পোর্ট
    networks:
      - smpp_network
    restart: always

  grafana:
    image: grafana/grafana:9.3.1
    depends_on:
      - prometheus # Grafana এর জন্য Prometheus প্রয়োজন
    volumes:
      - ./configs/${ENV:-dev}/grafana/provisioning:/etc/grafana/provisioning # Grafana প্রোভিশনিং
      - grafana_data:/var/lib/grafana
    ports:
      - "${GRAFANA_PORT:-3000}:3000" # Grafana ওয়েব পোর্ট
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin} # Grafana অ্যাডমিন পাসওয়ার্ড
    networks:
      - smpp_network
    restart: always

  # Email Service for Rate Uploads
  email-service:
    build:
      context: .
      dockerfile: ./deploy/docker/email-service/Dockerfile # এই Dockerfile এর কন্টেন্ট আপনার গাইডে দেওয়া নেই
    depends_on:
      - postgres
      - redis
      - rabbitmq
    volumes:
      - ./configs/${ENV:-dev}/email-service.conf:/etc/email-service/email-service.conf # কনফিগারেশন ফাইলের পাথ
      - email_attachments:/var/lib/email-service/attachments
    environment:
      - ENV=${ENV:-dev}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-smppdb}
      - DB_USER=${DB_USER:-smppuser}
      - DB_PASSWORD=${DB_PASSWORD:-smpppassword}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER:-smppuser}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-smpppassword}
      - IMAP_HOST=${IMAP_HOST:-imap.example.com} # ইমেইল সার্ভার (IMAP)
      - IMAP_PORT=${IMAP_PORT:-993} # IMAP পোর্ট
      - IMAP_USER=${IMAP_USER:-user} # ইমেইল ইউজারনেম
      - IMAP_PASSWORD=${IMAP_PASSWORD:-password} # ইমেইল পাসওয়ার্ড
      - EMAIL_POLLING_INTERVAL=${EMAIL_POLLING_INTERVAL:-300} # ইমেইল চেকিং বিরতি (সেকেন্ড)
    networks:
      - smpp_network
    restart: always

networks:
  smpp_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  smpp_logs:
  rate_manager_data:
  billing_data:
  invoice_templates:
  api_logs:
  prometheus_data:
  grafana_data:
  email_attachments: